// <auto-generated />
namespace Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sala777 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sala777));
        
        string IMigrationMetadata.Id
        {
            get { return "201801011917066_sala777"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
